package user

import (
	"context"
	"errors"

	"tms-core-service/internal/domain/entity"
	"tms-core-service/internal/domain/errs"
	"tms-core-service/internal/domain/repository"
	"tms-core-service/internal/infra/db/model"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type userRepo struct {
	db *gorm.DB
}

// NewUserRepository creates a new user repository
func NewUserRepository(db *gorm.DB) repository.UserRepository {
	return &userRepo{db: db}
}

// FindByID retrieves a user by ID
func (r *userRepo) FindByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	var user model.User
	if err := r.db.WithContext(ctx).First(&user, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errs.ErrNotFound
		}
		return nil, err
	}
	return user.ToEntity(), nil
}

// FindByEmail retrieves a user by email
func (r *userRepo) FindByEmail(ctx context.Context, email string) (*entity.User, error) {
	var user model.User
	if err := r.db.WithContext(ctx).Where("email = ?", email).First(&user).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errs.ErrNotFound
		}
		return nil, err
	}
	return user.ToEntity(), nil
}

// FindByPhoneNumber retrieves a user by phone number
func (r *userRepo) FindByPhoneNumber(ctx context.Context, phone string) (*entity.User, error) {
	var user model.User
	if err := r.db.WithContext(ctx).Where("phone_number = ?", phone).First(&user).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errs.ErrNotFound
		}
		return nil, err
	}
	return user.ToEntity(), nil
}

// Create creates a new user
func (r *userRepo) Create(ctx context.Context, user *entity.User) error {
	dbModel := model.FromEntity(user)
	if err := r.db.WithContext(ctx).Create(dbModel).Error; err != nil {
		if errors.Is(err, gorm.ErrDuplicatedKey) {
			return errs.ErrConflict
		}
		return err
	}
	// Update entity with ID if generated by DB
	user.ID = dbModel.ID
	return nil
}

// Update updates an existing user
func (r *userRepo) Update(ctx context.Context, user *entity.User) error {
	dbModel := model.FromEntity(user)
	result := r.db.WithContext(ctx).Save(dbModel)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return errs.ErrNotFound
	}
	return nil
}

// Delete soft deletes a user
func (r *userRepo) Delete(ctx context.Context, id uuid.UUID) error {
	result := r.db.WithContext(ctx).Delete(&model.User{}, "id = ?", id)

	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return errs.ErrNotFound
	}
	return nil
}

// List retrieves all users with pagination
func (r *userRepo) List(ctx context.Context, limit, offset int) ([]*entity.User, int64, error) {
	var dbUsers []*model.User
	var total int64

	if err := r.db.WithContext(ctx).Model(&model.User{}).Count(&total).Error; err != nil {
		return nil, 0, err
	}

	if err := r.db.WithContext(ctx).
		Limit(limit).
		Offset(offset).
		Find(&dbUsers).Error; err != nil {
		return nil, 0, err
	}

	entities := make([]*entity.User, len(dbUsers))
	for i, u := range dbUsers {
		entities[i] = u.ToEntity()
	}

	return entities, total, nil
}
